name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: squidfunk/mkdocs-material:7.3.6
    steps:
      - run: ls -lah ; pwd ; cd / ; find . -name "mkdocs.yml"
      - run: mkdocs gh-deploy --force
